### ISSUE TITLE
Surface Electrostatic Potential Per Residue - no pdb file

### ISSUE THREAD

**Issue by Mira2121** [djmaity/md-davis#10]
* MD DaVis version: latest
* Python version: 3.10
* Operating System: linux
* MSMS version: msms.x86_64Linux2.2.6.1
* delphi version: delphicpp_v8.4.5_serial

### Description
I am trying to find the "Surface Electrostatic Potential Per Residue". 
When trying to use the command "md-davis electrodynamics [OPTIONS] DIRECTORY", it did not work in command-line in linux. Then, when I used the Gui interface in command-line (in linux), the electrodynamics command is outputting a pymol_session.pse file, but no pdb file with the b-factor column populated with the respective averaged potentials (per residue or per atom). How to get this pdb file? 
I checked the installation files, and do see that pymol version 2.5.0 got compiled properly. Why do I get the .pse file (can open it in pymol, pse session looks good), but not the pdb?
Thanks

**Comment by djmaity** [comment]
The `md-davis electrodynamics` is designed to create a PyMOL session to visualize electric field dynamics around a protein for multiple frames of an MD trajectory.

To obtain a PDB file with the electrostatic potentials in the B-factor column:

1. Please reinstall md-davis with the latest changes from GitHub.

2. Calculate the electrostatics using: 
```md-davis electrostatics --surface -m ~/msms_i86_64Linux2_2.6.1/msms.x86_64Linux2.2.6.1 -d ~/delphicpp_v8.4.5_serial -o output_directory -g 401 protein.pdb```

Make sure to choose an appropriate odd integer gird size with `-g` depending on the size of your protein.

3. Create a PDB file with the potentials in the B-factor column with:
```md-davis potential_into_pdb output_directory/protein.pot protein.pdb protein_output.pdb```

`protein.pot` is the potential file written by the `md-davis electrostatics` command in the output directory. Please check `md-davis potential_into_pdb --help` for a complete list of options. Feel free to adapt the code in [potential_into_pdb.py](https://github.com/djmaity/md-davis/blob/master/md_davis/electrostatics/potential_into_pdb.py)  for your use case.
